### ISSUE TITLE
slush stencil develop task errors.

### ISSUE THREAD

**Issue by ericwebster** [ronik-design/slush-stencil#8]
Hey Gang,

Checking out the slush stencil tool you have created and I am running into a bit of resistance.

First I tried a "react" project, when I ran into issues getting it to run I tried creating a backbone project.

The specific issue I am running into is that I am getting the following error.

``` javascript
    Message:
        An error occured in task 'develop'.
    [15:51:31] 'watch' errored after 1.02 s
    [15:51:31] Error: task completion callback called too many times
        at finish (/Users/ewebster/Projects/sandbox/stencil-backbone/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:15:10)
        at cb (/Users/ewebster/Projects/sandbox/stencil-backbone/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
        at watchStart (/Users/ewebster/Projects/sandbox/stencil-backbone/gulpfile.js:77:5)
        at finish (/Users/ewebster/Projects/sandbox/stencil-backbone/node_modules/run-sequence/index.js:62:5)
        at Gulp.onError (/Users/ewebster/Projects/sandbox/stencil-backbone/node_modules/run-sequence/index.js:69:4)
        at emitOne (events.js:82:20)
        at Gulp.emit (events.js:169:7)
        at Gulp.Orchestrator._emitTaskDone (/Users/ewebster/Projects/sandbox/stencil-backbone/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
        at /Users/ewebster/Projects/sandbox/stencil-backbone/node_modules/gulp/node_modules/orchestrator/index.js:275:23
        at finish (/Users/ewebster/Projects/sandbox/stencil-backbone/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    [15:51:31] 'build' errored after 1.02 s
    [15:51:31] Error in plugin 'run-sequence'
    Message:
        An error occured in task 'lint'.
```

The steps I used were as follows;
- installed slush-stensil via npm
- ran "slush stencil"
- ran "npm install"
- ran "gulp develop"

In addition to the error above, there were also large amounts of lint errors too, assumed I would not see those as well.

A small taste of those;

``` javascript
    scripts/App.js
       1:1   error  Filename 'scripts/App.js' does not match the naming convention  filenames/filenames
       7:9   error  Expected indentation of 6 space characters but found 8          indent
```

I'm sure I'm not doing something right, but can't figure it out.

For what its worth, I am on a MacBook Pro running 10.10.5

**Comment by mshick** [comment]
@ericwebster I'm sorry about the delay here... What I can say is, I really haven't been keeping up the backbone or react flavors of the generator and they've gotten behind. Honestly, I think I just need to remove them because I can't imagine using Backbone again internally, and React is so fussy I would find it hard to adequately scaffold anything useful.

I can say, the basic generator _does_ work. What I might do here is just offer two variations, our little knockout-centric framework, for enhancing fairly simple web sites, and a "go your own way" variation that will provide some basic build tools for scripts and look at a `main.js` file to get going, but would require you to install all client js dependencies on your own.

Maybe that doesn't help you immediately though. I'm going to work on this very soon, and if you haven't moved on already I would love your feedback.

**Comment by ericwebster** [comment]
Ok .. Knockout was the only one I didn't try .. Ill give that one a go.
